main: '${project.groupId}.${project.name}'
name: '${project.name}'
version: '${project.version}'
website: '${project.url}'
description: '${project.description}'
api-version: '1.17'
authors: [JustEli]
softdepend: [Vault, Treasury, WorldGuard, mcMMO, MythicMobs]
libraries:
  - org.bstats:bstats-bukkit:3.0.0
commands:
  coins:
    description: 'Command for showing all available commands from Coins. Also used for various admin tools.'
    permission: 'coins.command'
    usage: '/<command> [reload|settings|drop|remove|language|version|toggle]'
    aliases:
      - coin
  withdraw:
    description: 'Withdraw money from your balance into physical coins.'
    permission: 'coins.withdraw'
    usage: '/<command> <worth> [amount]'
permissions:
  coins.command:
    default: true
  coins.command.reload:
    default: op
  coins.command.settings:
    default: op
  coins.command.drop:
    default: op
  coins.command.remove:
    default: op
  coins.command.language:
    default: op
  coins.command.version:
    default: op
  coins.command.toggle:
    default: op
  coins.withdraw:
    description: 'Access to the /withdraw command, and ability to withdraw and deposit coins.'
    default: op
  coins.multiplier.n:
    description: 'Permission to give to players who should get multiplied coin drops. Replace /n/ with a number.'
    default: false
  coins.disable:
    description: 'Permission to give to players to disable coin pickup for them.'
    default: false
  coins.spawner:
    description: 'Permission to give to players who should get coins from killing mobs from spawners.'
    default: false
